# Generated by Django 4.2.3 on 2023-09-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('ScName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ScHead', models.CharField(max_length=100)),
                ('ScLoc', models.CharField(max_length=100)),
            ],
        ),
    ]
